### ISSUE TITLE
SQLAlcehmy unique prevents edit on model

### ISSUE THREAD

**Issue by sbehrens** [flask-admin/flask-admin#1007]
Even if a user edits a model and only updates non unique fields, the application throws an error  suggesting that when a user edits something every field is updated regardless if it is changed or not.  This prevents a user from restricting the creation of models with a unique name, but editing a model and adding an additional optional attribute like email.

Confirmed on Flask-Admin==1.2.0

**Comment by pawl** [comment]
@sbehrens I'm having trouble reproducing this one with this gist: https://gist.github.com/pawl/edeb9d1f974d34f3da7a

**Comment by pawl** [comment]
Closing this until we can get more details on how to reproduce this issue.

**Comment by pawl** [comment]
Nevermind, looks like there's other issues already open for this in #782, #946, #486

There's a workaround mentioned here: https://github.com/flask-admin/flask-admin/issues/486#issuecomment-38859637

**Comment by pawl** [comment]
Made a comment here: https://github.com/Netflix/sleepy-puppy/issues/7#issuecomment-206670213

It's an issue caused by using flask_wtf's Form as flask-admin's base form. If you're using it just for csrf validation, I'd recommend using flask-admin's SecureForm: https://flask-admin.readthedocs.org/en/latest/advanced/#enabling-csrf-protection
