### ISSUE TITLE
contrib.sqla.ModelView wrong count for polymorphic models

### ISSUE THREAD

**Issue by gnunicorn** [flask-admin/flask-admin#1062]
Looks like `self.session.query(func.count('*')).select_from(self.model)` doesn't take into account the proper sub-selecting on [polymorphic models](http://docs.sqlalchemy.org/en/rel_1_0/orm/inheritance.html?highlight=polymorphic#single-table-inheritance): it counts over the entire base class not subselecting for the specific polymorphic entry. Resulting in a mis-match of items counted and found (including paging and alike):

![screen shot 2015-10-01 at 13 05 20](https://cloud.githubusercontent.com/assets/40496/10219218/47548fd4-683d-11e5-8f46-4c50bbad77c4.png)

**Comment by ligthyear** [comment]
Replacing it with `self.session.query(func.count('*')).select_from(self.model.query.selectable)` fixes the problem here – but I don't know how sound-proof that is (is `model.query` always there?), so I put it behind a `if 'polymorphic_identity' in self.model.__mapper_args__:` and only use it for my polymorphic cases.

**Comment by petrus-jvrensburg** [comment]
It looks like the workaround works well enough. I'm closing this, but please re-open if it's still a problem.
