### ISSUE TITLE
Localization issues regarding inline models

### ISSUE THREAD

**Issue by ArthurPBressan** [flask-admin/flask-admin#1120]
I found a couple issues regarding the localization on inline models:
1. When adding inline models, the "New %model" isn't translated.
2. We should be able to configure the singular name of the inline model. Right now it's using the parent view `column_label` configuration for both the field name and for each singular model, and that label (in my case) is always a plural word. I think adding a `singular_label` to `InlineFormAdmin` could solve it.

**Comment by pawl** [comment]
The goal is to make it more similar to django, like this?: ![django example](https://i.imgur.com/PjZ9RX7.png)

So there's 2 problems:
1. "New" in the templates is not translated. This should be a quick fix. There are already translations for "Add" and "Create" but no "New" yet. I might change it to "Add" instead. 
2. Labels to the left of inline models on the form aren't plural. This is a harder one, would need to alling adding a plural name for the column.

Django has an interesting approach to the 2nd one: https://docs.djangoproject.com/en/dev/ref/models/options/#verbose-name-plural

By default they add an "s" to make the plural name. I think that's worse than not making it plural at all, because that would almost always be wrong in other languages.

**Comment by ArthurPBressan** [comment]
Actually, it's the label for each inline model that's plural in my case. Consider the following SQLAlchemy relationship:

```python
class Parent(Base):
    __tablename__ = 'parent'
    id = Column(Integer, primary_key=True)
    children = relationship("Child", backref="parent")

class Child(Base):
    __tablename__ = 'child'
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey('parent.id'))
```

In the `Parent` admin, it will show "Children" in the left-side column and, for each child model, they will be labelled as "Children # 1, Children # 2", and so on. It should be "Child # 1, Child # 2" and so on.

Even in this simple example, we can see that there's no reliable way for detecting what would be the singular of "Children" (or plural of "Child"). This is why I think it's simpler to add a `singular_label` to the `InlineFormAdmin`.

----
I think the idea behind Django's algorithm to add an "s" to the end of the name is because they will mostly get it right when it's in English, which is probably the language most Django projects are in, or at least, the language most Django core developers speak. As you said, it is probably wrong in most other languages, but that's why it is easily configurable.

**Comment by petrus-jvrensburg** [comment]
I think this has been fixed, but please re-open if it's still a problem.
