### ISSUE TITLE
bootstrap2-editable.min.js and bootstrap3-editable.min.js contain 2015 as maxYear

### ISSUE THREAD

**Issue by flobr** [flask-admin/flask-admin#1269]
Hello!
In both files maxYear is 2015 and not 2016:

fn.combodate.defaults = {
        format: "DD-MM-YYYY HH:mm",
        template: "D / MMM / YYYY   H : mm",
        value: null,
        minYear: 1970,
        maxYear: 2015,
        yearDescending: !0,
        minuteStep: 5,
        secondStep: 1,
        firstItem: "empty",
        errorClass: null,
        roundTime: !0,
        smartDays: !1
    }

Could you please increase it? Or even better set it to actual year?

Thank you!

**Comment by illume** [comment]
#1018 is related to this. It describes changing minYear.

**Comment by ozooner** [comment]
For me the issue is still present.
@pawl in his commit message:
`update x-editable to e03afb2436056593d64f0f01f575f0f091d00785`

The source in repo clearly has maxDate hardcoded to 2015:
https://github.com/vitalets/x-editable/blob/e03afb2436056593d64f0f01f575f0f091d00785/dist/bootstrap-editable/js/bootstrap-editable.js#L4421
