### ISSUE TITLE
Case insensitive search with mongo

### ISSUE THREAD

**Issue by ptbrowne** [flask-admin/flask-admin#1338]
When you search something using the mongo engine, [$regex is used to query the database](https://github.com/flask-admin/flask-admin/blob/e8aaf73b77b25550b94c137646e51588d36adb06/flask_admin/contrib/pymongo/view.py#L189). However the case insensitive flag is not set.

For ease of use and to be [coherent with mod_contrib_sqla that uses ILIKE](https://flask-admin.readthedocs.io/en/latest/api/mod_contrib_sqla/?highlight=ilike#flask_admin.contrib.sqla.ModelView.column_searchable_list), I think the flag should be added automatically.

I am open to do the PR.

**Comment by mrjoes** [comment]
Sure, please open a pull request - it should do case-insensitive search by default.

**Comment by gordol** [comment]
The same is true for mongoengine as well...

https://github.com/flask-admin/flask-admin/blob/c8fdf7400e2d82d8d7d1a85b6255b9cd9d701c41/flask_admin/contrib/mongoengine/tools.py

However, is it fair to compare SQL to NoSQL? In SQL, case sensitivity has nothing to do with the LIKE command, and everything to do with the collation.

The question is, since we'd be inverting the sensitivity logic here, what character should be used to denote the search term as being case sensitive? Is it not better to use * at the start of the string, like in mongoengine, instead of insensitive by default?

Otherwise, we have diverging search logic from one database to another, which may not be expected by end users.

**Comment by ptbrowne** [comment]
I did not know about *. Thanks @gordol.

It meets my need but I think that in the case of flask-admin, it is much more likely that the user wants a search to be case insensitive by default. To me, it would be more useful to have * mean case sensitive.

**Comment by gordol** [comment]
I think we should assume the query is case insensitive unless an uppercase character is present in the query string.


What if we had a more extensible search mechanism? With toggles for things like case sensitivity, outside of the query string, through parameterized flags, and exposed through, say, a drop down menu or set of checkboxes.

**Comment by ptbrowne** [comment]
> I think we should assume the query is case insensitive unless an uppercase character is present in the query string.

Agree, apparently this behavior already exists in vim and is called smartcase.

> What if we had a more extensible search mechanism? With toggles for things like case sensitivity, outside of the query string, through parameterized flags, and exposed through, say, a drop down menu or set of checkboxes.

This sounds too complex to me, I think flask-admin should remain as simple as positive and pick smart defaults.

**Comment by gordol** [comment]
> Agree, apparently this behavior already exists in vim and is called smartcase.

That's why I suggested it. ;)

>  I think flask-admin should remain as simple as positive and pick smart defaults.

Agreed.

**Comment by petrus-jvrensburg** [comment]
closed in #865
