### ISSUE TITLE
Getting model view query with filters applied

### ISSUE THREAD

**Issue by PhilippeMenard** [flask-admin/flask-admin#1806]
Hi,

I am looking for a way to get the view query object from a list view, with filters applied.

I have found the following [answer](https://stackoverflow.com/questions/47124728/how-do-you-add-a-summary-row-for-flask-admin) on Stack Overflow but accessing `self.session.query` inside the `render` function override does not have filters applied.

Is there a built in way to get the query including filters ?
Thanks!

**Comment by mrjoes** [comment]
Here's a query builder: https://github.com/flask-admin/flask-admin/blob/master/flask_admin/contrib/sqla/view.py#L1002

You can pass `execute=False` to get a query object instead of the filtered list.

And here's how it's being used: https://github.com/flask-admin/flask-admin/blob/master/flask_admin/model/base.py#L1959 - you can use same helpers to collect filters, etc.

**Comment by PhilippeMenard** [comment]
Thank you very much for pointing me in the right direction! It works perfectly
