### ISSUE TITLE
the attribute column_extra_row_actions in bootstrap4 not working

### ISSUE THREAD

**Issue by EchoShoot** [flask-admin/flask-admin#2306]
the attribute column_extra_row_actions in bootstrap4 not working

```python
class RuleModelView(ModelView):
    column_extra_row_actions = [
        EndpointLinkRowAction('glyphicon glyphicon-play', '.redirect_to_xpath_view'),
    ]  # 影响每行的 action

    @expose('/view_xpath', methods=['GET'])
    def redirect_to_xpath_view(self):
        return redirect(url_for('AdminXpath'))
```

**Comment by BenjaminLECHA** [comment]
It's hard to help without error message but probably due to the path of your view.

According to the documentation : https://flask-admin.readthedocs.io/en/latest/api/mod_model/?highlight=EndpointLinkRowAction#flask_admin.model.BaseModelView.column_extra_row_actions

You should refer a view (or the name of a Blueprint) follow by the path name.

Exemple :

'my_view.index_view'
'bp_name.route_name'

Here you try to use . fot the context like the class itself. The best way to fix your problem should be to remove your expose and redirect and replace '.redirect_to_xpath_view' by the orignal 'view/bp.route_name' of your AdminXpath (If you haven't create you route (redirect) outside the class).
