### ISSUE TITLE
Delete fails CSRF validation

### ISSUE THREAD

**Issue by cybertoast** [flask-admin/flask-admin#372]
I'm using a Mongo back-end, and have flask-wtf CSRF validation. When i attempt to delete a record (or bulk delete all records from the list view) I get a CSRF validation failure because the request does not have the X-CSRFToken in the POST request header. I wonder if this is something I need to configure.

Please let me know if you need a test case for this, but basically I've enabled CSRF with `flask_wtf.CsrfProtect(app)`.

Thanks

**Comment by pawl** [comment]
I made some basic tests for CSRF validation: https://github.com/pawl/flask-admin/blob/ae0cd1ef00e31cbcb98491399a35a4b96817ca25/flask_admin/tests/sqla/test_csrf.py

The delete test fails because the delete_view never validates the token, and "{{ csrf_token() }}" never prints anything because that variable never exists.

I'm up for fixing it, but I want to wait until after pull request #756 is merged. I don't want to create any merge conflicts.
