### ISSUE TITLE
Cause possible data loss when form_edit_rules do not display some columns

### ISSUE THREAD

**Issue by Eliacy** [flask-admin/flask-admin#686]
Take the following models as an example:

    class Image(db.Model):
        id = db.Column(db.Integer, primary_key=True) 
        path = db.Column(db.String(120), default='')
        user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
        user = db.relationship('User', backref=db.backref('images', lazy='dynamic'), foreign_keys=[user_id])
        
    class User(db.Model):
        id = db.Column(db.Integer, autoincrement='ignore_fk', primary_key=True)
        username = db.Column(db.String(80), unique=True, default='')

I'd like to record who uploaded detailed images, but one user could relate to hundreds of images, and make the User edit form to be super slow to load. So I decide to hide 'images' column in User edit form, and write down the following code:

    class UserView(ModelView):
        form_edit_rules = ('username')

Then when I submit a modification of a user instance, all his/her 'images' value will be wiped to be '[]', and all these images instances will lose their original 'user_id' value. It is because the form param to 'update_model(self, form, model):' still keep an empty 'images' item.

I think columns not in form_edit_rules should not be modified, that will be a more straightforward mechanism. Thanks.

**Comment by larkin** [comment]
@mrjoes I was thinking that "sensible logic" would be that any field that is not rendered in the page should also be excluded from the form so that it doesn't override the form with default values.  Similar to `form_columns`, a column that is excluded because of `form_edit_rules` should be excluded from the form and not rendered nor expected in the response.

Any reason why this shouldn't be so?

**Comment by mrjoes** [comment]
It will be hard to do it in generic way - one can implement custom rule and even nest them. Probably it should be possible to implement following logic:

1. In rule constructor contribute column to list of rendered columns
2. Compare list of rendered columns with `form_columns` and show a warning if they don't match

**Comment by larkin** [comment]
I may be missing something here, but couldn't this be resolved with a change to `BaseModelView.edit_view` and `BaseModelView.create_view`: after instantating a form, we can generate a list of visible fields based on `form_rules` and remove non-visible fields?

Here's a pseudo-patch for `BaseModelView.edit_view`-- can you explain to me what would be the downsides or problems with the following solution?  If it's a reasonable avenue for this, I'm happy to pursue it further.


```python
    @expose('/edit/', methods=('GET', 'POST'))
    def edit_view(self):
        """
            Edit model view
        """
        return_url = get_redirect_target() or self.get_url('.index_view')

        if not self.can_edit:
            return redirect(return_url)

        id = get_mdict_item_or_list(request.args, 'id')
        if id is None:
            return redirect(return_url)

        model = self.get_one(id)

        if model is None:
            return redirect(return_url)

        form = self.edit_form(obj=model)

        # walk rules to get a flat list of visible fields / deal with logic.
        visible_fields = set()
        for rule in self._form_edit_rules:
          if isinstance(rule, basestring):
            visible_fields.add(field)
          elif isinstance(rule, rules.Nested):
            # recurse through nested
          elif # Handle other rule types
        
        # remove fields 
        for field in form:
          if field.name not in visible_fields:
            form.__delitem__(field.name)

        if self.validate_form(form):
            if self.update_model(form, model):
                if '_continue_editing' in request.form:
                    flash(gettext('Record was successfully saved.'))
                    return redirect(request.url)
                else:
                    return redirect(return_url)

        if request.method == 'GET':
            self.on_form_prefill(form, id)

        form_opts = FormOpts(widget_args=self.form_widget_args,
                             form_rules=self._form_edit_rules)

        return self.render(self.edit_template,
                           model=model,
                           form=form,
                           form_opts=form_opts,
                           return_url=return_url)
```

**Comment by mrjoes** [comment]
Yes, it is different.

`form_columns` control wtform form fields. Originally form rendering was dumb - it was iterating on form fields and drawing them one by one.

`form_rules` are completely different. They tell Flask-Admin how to draw fields in a form. Think of it as a set of rules that are executed one by one to draw a form. `form_rules` are not limited by form fields - it is possible to render anything, nest rules, etc. It is way bigger than just a field list.

Your solution is not flexible - in order to add custom rule that renders field, one will have to monkey-patch edit view. 

Only solution I can think of - rules tell View class which fields are going to be rendered. This way View will be able to figure out if `form_columns` match list of rendered rules.

**Comment by larkin** [comment]
That code was primarily to demonstrate where the logic to remove fields would be injected, but as you point out, the logic for determining which fields are exposed by a given rule should be defined by the rule, not by the view.  The view would have a convenience method like `remove_hidden_fields(form, self._form_edit_rules)`, and each rule will know how to figure out fields used by it's children.

I'll take a stab at it and start up a pull request-- sound good?
