### ISSUE TITLE
"Save" button on Create Mode sometimes doesn't return to List View

### ISSUE THREAD

**Issue by fzumstein** [flask-admin/flask-admin#906]
This is a bug that was introduced with v1.2.0:

e.g. running this example: https://github.com/flask-admin/flask-admin/tree/master/examples/sqla/app.py will not return to the List view when adding a new user with v1.2.0. It works correctly when using v1.1.0.

**Comment by mrjoes** [comment]
Default behavior was changed, see this: https://github.com/flask-admin/flask-admin/pull/831

**Comment by fzumstein** [comment]
Ok makes sense. However, there's something else going on: When I hit "save", the `List/Create` tabs are gone (again trying out the same sample as above). When I hit "save and continue", everything is as expected (form clears and `List/Create` tabs are still there).

**Comment by mrjoes** [comment]
It happens because you're redirected to edit view after successful creation of the record. And edit view does not have navigation tabs by default.

See here:
https://github.com/flask-admin/flask-admin/blob/master/flask_admin/templates/bootstrap3/admin/model/create.html#L15
https://github.com/flask-admin/flask-admin/blob/master/flask_admin/templates/bootstrap3/admin/model/edit.html#L14

**Comment by fzumstein** [comment]
Ok I see, the inconsistent behavior was caused by `can_edit = False` which will obviously have it return to the list-view directly with `Create > Save`.

I question though the choice of the default: It feels awkward to `Create > Save > Cancel` to add a single record, but I guess this goes into another issue. So feel free to close this one.

**Comment by fzumstein** [comment]
I've listed my concerns directly in #831 so I am closing this one.
